[package]
name = "nymstr-group"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "sync", "io-util", "io-std"] }
tokio-stream = "0.1"
fern = { version = "0.6", features = ["colored"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
sha2 = "0.10"
base64 = "0.21"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "chrono"] }
nym-sdk = { git = "file:///Users/zmain/nymstr/nym", branch = "develop" }
uuid = { version = "1", features = ["v4"] }
rand = "0.8"
toml = "0.8"
ed25519-zebra = { version = "4.1", features = ["alloc"] }
async-trait = "0.1"
nymstr-common = { path = "../crates/nymstr-common" }
nymstr-crypto = { path = "../crates/nymstr-crypto" }
nymstr-transport = { path = "../crates/nymstr-transport" }

[dev-dependencies]
tempfile = "3"
chrono = "0.4"
serde_json = "1.0"